FROM python:3.10  

WORKDIR /app

COPY . .
RUN pip3 install -r requirements.txt

EXPOSE 5000

ENTRYPOINT [ "python3", "-m", "flask", "run", "--host=0.0.0.0" ]




# FROM python:latest is also valid
# RUN apt-get update && apt-get upgrade -y
# RUN apt-get install nginx -y
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]

